unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind r source-file ~/.tmux.conf


bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -gq allow-passthrough all
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

set -g mouse on
set -g status-left-length 25
set -g pane-border-status top
set -g pane-border-format " [ #P #{pane_current_command} ] "

set -g set-clipboard

set -sg escape-time 0
bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"

set -g default-terminal "xterm-256color"

set-option -g history-limit 50000
